chore(release): publish [skip ci]
- jest-preset-miaoxing@0.2.1
- @miaoxing/dev@6.1.2
- append-url@1.0.4
- image-view2@0.1.4
- miaoxing@0.1.5
- @mxjs/bootstrap@0.1.1
- @mxjs/a-date-range-picker@0.1.0
- @mxjs/a-page@0.2.1
- @mxjs/a-region-cascader@0.1.0
- @mxjs/app@0.2.1
- @mxjs/cur-url@0.2.1
- @mxjs/a-form@0.2.1
- @mxjs/a-table@0.2.1
- @mxjs/form@0.2.1
- @mxjs/a-button@0.2.1
- @mxjs/test@0.1.0
- @mxjs/webpack@0.1.1
- @wei/wei@0.9.31
- @miaoxing/plugin@0.2.3
- @miaoxing/api@0.1.11
- @miaoxing/services@0.2.3
- @miaoxing/app@0.2.3
- @miaoxing/admin@0.2.3
- @miaoxing/region@0.1.0
- @miaoxing/address@0.1.0
- @miaoxing/captcha@0.1.11
- @miaoxing/link-to@0.1.3
- @miaoxing/category@0.1.0
- @miaoxing/config@0.1.11
- @miaoxing/install@0.2.3
- @miaoxing/logistics@0.1.0
- @miaoxing/mail@0.1.3
- @miaoxing/nav@0.1.3
- @miaoxing/product@0.1.0
- @miaoxing/payment@0.1.0
- @miaoxing/queue@0.1.11
- @miaoxing/seq@0.1.11
- @miaoxing/sms@0.1.3
- @miaoxing/verify-code@0.1.3
- @miaoxing/user@0.1.12
- @miaoxing/cart@0.1.0
- @miaoxing/order@0.1.0
- @miaoxing/refund@0.1.0

# jest-preset-miaoxing

## [0.2.1](https://github.com/twinh/miaoxing/compare/jest-preset-miaoxing@0.2.0...jest-preset-miaoxing@0.2.1) (2020-09-25)

### Features

* setup.js 增加常用的 window.matchMedia 方法 ([62c4e64](https://github.com/twinh/miaoxing/commit/62c4e648431ec81521f2f8a843cd93fc6c64a1f5))

# @miaoxing/dev

## [6.1.2](https://github.com/twinh/miaoxing/compare/@miaoxing/dev@6.1.1...@miaoxing/dev@6.1.2) (2020-09-25)

### Bug Fixes

* 指定 jest-cli 版本，解决 "TypeError: (0 , _jestUtil(...).formatTime) is not a function" ([4b94fc4](https://github.com/twinh/miaoxing/commit/4b94fc4997f6ea1a5b2b4126c626f4885d517c60))

### Dependencies

* **jest-preset-miaoxing:** upgrade from 0.2.0 to 0.2.1

# append-url

## [1.0.4](https://github.com/twinh/miaoxing/compare/append-url@1.0.3...append-url@1.0.4) (2020-09-25)

### Dependencies

* **@miaoxing/dev:** upgrade from 6.1.1 to 6.1.2

# image-view2

## [0.1.4](https://github.com/twinh/miaoxing/compare/image-view2@0.1.3...image-view2@0.1.4) (2020-09-25)

### Dependencies

* **@miaoxing/dev:** upgrade from 6.1.1 to 6.1.2

# miaoxing

## [0.1.5](https://github.com/twinh/miaoxing/compare/miaoxing@0.1.4...miaoxing@0.1.5) (2020-09-25)

### Dependencies

* **@miaoxing/dev:** upgrade from 6.1.1 to 6.1.2

# @mxjs/bootstrap

## [0.1.1](https://github.com/twinh/miaoxing/compare/@mxjs/bootstrap@0.1.0...@mxjs/bootstrap@0.1.1) (2020-09-25)

### Features

* 增加 Media 组件 ([affb6eb](https://github.com/twinh/miaoxing/commit/affb6eb196379e6035bb8b77460c7baa9e3b5489))

# @mxjs/a-date-range-picker

# 0.1.0 (2020-09-25)

### Features

* 增加 DateRangePicker ([2494232](https://github.com/twinh/miaoxing/commit/2494232f46920c901638431815e86560f542bfab))

### Dependencies

* **@miaoxing/dev:** upgrade from 6.1.1 to 6.1.2

# @mxjs/a-page

## [0.2.1](https://github.com/twinh/miaoxing/compare/@mxjs/a-page@0.2.0...@mxjs/a-page@0.2.1) (2020-09-25)

### Features

* 增加 PageContext 以便外部提供 pages 值 ([554e126](https://github.com/twinh/miaoxing/commit/554e1261ae1126aea0f14696fa1c47a400946487))

# @mxjs/a-region-cascader

# 0.1.0 (2020-09-25)

### Features

* 增加区域选择插件 ([83466fe](https://github.com/twinh/miaoxing/commit/83466feb5dd50727ebf503dee0d3e97a7dd30433))

### Dependencies

* **@miaoxing/dev:** upgrade from 6.1.1 to 6.1.2

# @mxjs/app

## [0.2.1](https://github.com/twinh/miaoxing/compare/@mxjs/app@0.2.0...@mxjs/app@0.2.1) (2020-09-25)

### Bug Fixes

* **Router:** 没有匹配到页面, page.params 错误 ([1d9cdab](https://github.com/twinh/miaoxing/commit/1d9cdabd690123c7a017cbd960d6bd0de5361f74))

### Dependencies

* **append-url:** upgrade from 1.0.3 to 1.0.4
* **@miaoxing/dev:** upgrade from 6.1.1 to 6.1.2

# @mxjs/cur-url

## [0.2.1](https://github.com/twinh/miaoxing/compare/@mxjs/cur-url@0.2.0...@mxjs/cur-url@0.2.1) (2020-09-25)

### Dependencies

* **@mxjs/app:** upgrade from 0.2.0 to 0.2.1
* **@miaoxing/dev:** upgrade from 6.1.1 to 6.1.2

# @mxjs/a-form

## [0.2.1](https://github.com/twinh/miaoxing/compare/@mxjs/a-form@0.2.0...@mxjs/a-form@0.2.1) (2020-09-25)

### Features

* 增加 FormContext，可用于子组件获取 form 对象 ([96503a5](https://github.com/twinh/miaoxing/commit/96503a59270f3ea9f2a50089c70800c2f738f03a))
* **SearchForm:** 增加 filterValues 回调，用于在搜索前更改表单的值 ([c674f7c](https://github.com/twinh/miaoxing/commit/c674f7c6647278d75d42087dce141c17fd31be81))
* FromItem 增加 textarea 支持 ([1628b29](https://github.com/twinh/miaoxing/commit/1628b2905173883964cd71dd0ac3777034d0dcbf))
* 增加 afterLoad 回调，可以用于更改请求的返回值 ([4e4e861](https://github.com/twinh/miaoxing/commit/4e4e861000c22edd8b458d296364cfeb033d6cdc))

### Dependencies

* **@mxjs/cur-url:** upgrade from 0.2.0 to 0.2.1
* **miaoxing:** upgrade from 0.1.4 to 0.1.5
* **@miaoxing/dev:** upgrade from 6.1.1 to 6.1.2

# @mxjs/a-table

## [0.2.1](https://github.com/twinh/miaoxing/compare/@mxjs/a-table@0.2.0...@mxjs/a-table@0.2.1) (2020-09-25)

### Bug Fixes

* `id` 属性允许字符串和数字 ([60ad497](https://github.com/twinh/miaoxing/commit/60ad497df68b8698930c1baddd57c4b1c4729c78))

### Dependencies

* **@mxjs/cur-url:** upgrade from 0.2.0 to 0.2.1
* **append-url:** upgrade from 1.0.3 to 1.0.4
* **miaoxing:** upgrade from 0.1.4 to 0.1.5
* **@miaoxing/dev:** upgrade from 6.1.1 to 6.1.2

# @mxjs/form

## [0.2.1](https://github.com/twinh/miaoxing/compare/@mxjs/form@0.2.0...@mxjs/form@0.2.1) (2020-09-25)

### Dependencies

* **@miaoxing/dev:** upgrade from 6.1.1 to 6.1.2

# @mxjs/a-button

## [0.2.1](https://github.com/twinh/miaoxing/compare/@mxjs/a-button@0.2.0...@mxjs/a-button@0.2.1) (2020-09-25)

### Dependencies

* **@mxjs/bootstrap:** upgrade from 0.1.0 to 0.1.1
* **miaoxing:** upgrade from 0.1.4 to 0.1.5
* **@miaoxing/dev:** upgrade from 6.1.1 to 6.1.2

# @mxjs/test

# 0.1.0 (2020-09-25)

### Features

* 增加 bootstrap 方法，加载插件启动必须的方法 ([b7840a8](https://github.com/twinh/miaoxing/commit/b7840a819b5a9aa9d3cb0d5d649d94ef4c75246c))
* 增加 mxjs/test, 提供常用的测试工具方法 ([e002196](https://github.com/twinh/miaoxing/commit/e0021965bad800b60c6d99f1af6fd998492b1816))

# @mxjs/webpack

## [0.1.1](https://github.com/twinh/miaoxing/compare/@mxjs/webpack@0.1.0...@mxjs/webpack@0.1.1) (2020-09-25)

### Bug Fixes

* 忽略测试文件 ([1d2ac9e](https://github.com/twinh/miaoxing/commit/1d2ac9e00e90a2ef6b0b55d8cbb579bd29b1644e))

# @wei/wei

## [0.9.31](https://github.com/twinh/miaoxing/compare/@wei/wei@0.9.30...@wei/wei@0.9.31) (2020-09-25)

### Bug Fixes

* **V:** 链接验证服务每次调用都应创建新的对象 ([f4624ae](https://github.com/twinh/miaoxing/commit/f4624ae2e1411c7324dfbad1223f9c3b902e141a))

### Features

* **Pinyin:** 获取拼音可以设置分隔符 ([f2e2666](https://github.com/twinh/miaoxing/commit/f2e266676427fe9eb509943af9557f2c1095e4c0))

### Dependencies

* **@miaoxing/dev:** upgrade from 6.1.1 to 6.1.2

# @miaoxing/plugin

## [0.2.3](https://github.com/twinh/miaoxing/compare/@miaoxing/plugin@0.2.2...@miaoxing/plugin@0.2.3) (2020-09-25)

### Bug Fixes

* date/datetime 自动转换 null 为空字符串导致数据库出错 ([c6f6b6b](https://github.com/twinh/miaoxing/commit/c6f6b6bf3aba56f0c9b6c308f9f539f724123e53))
* 生成 metadata 的数据表缺少前缀 ([f50b1f8](https://github.com/twinh/miaoxing/commit/f50b1f89512bc327a5ce724d13b6c6aa931690ae))
* **model:** 多个记录加载多个记录时，关联数据可能变空 ([173d915](https://github.com/twinh/miaoxing/commit/173d9156323e89b8f00287162274883764dc5f12))

### Features

* ReqQuery 支持数组形式的范围查找 ([b808bec](https://github.com/twinh/miaoxing/commit/b808becf78bdd3a4c883ec49af61404b8dc85d59))
* 允许调用 XxxModel::toArray ([9e82525](https://github.com/twinh/miaoxing/commit/9e825251b7afbb8a3500d53d7dc62d5d9982cc33))

### Dependencies

* **@miaoxing/dev:** upgrade from 6.1.1 to 6.1.2
* **@wei/wei:** upgrade from 0.9.30 to 0.9.31

# @miaoxing/api

## [0.1.11](https://github.com/twinh/miaoxing/compare/@miaoxing/api@0.1.10...@miaoxing/api@0.1.11) (2020-09-25)

### Dependencies

* **@miaoxing/plugin:** upgrade from 0.2.2 to 0.2.3
* **@miaoxing/dev:** upgrade from 6.1.1 to 6.1.2

# @miaoxing/services

## [0.2.3](https://github.com/twinh/miaoxing/compare/@miaoxing/services@0.2.2...@miaoxing/services@0.2.3) (2020-09-25)

### Features

* 增加 coll 和 item 相关操作的 trait ([bfe663d](https://github.com/twinh/miaoxing/commit/bfe663d98231e5c1f1ea067e56608bef92167047))
* **Convention:** getModelName 支持传入页面匿名类 ([7987ae4](https://github.com/twinh/miaoxing/commit/7987ae4b3862e5cb7f0fe504200902d78699c23e))

### Dependencies

* **@miaoxing/dev:** upgrade from 6.1.1 to 6.1.2
* **@miaoxing/plugin:** upgrade from 0.2.2 to 0.2.3

# @miaoxing/app

## [0.2.3](https://github.com/twinh/miaoxing/compare/@miaoxing/app@0.2.2...@miaoxing/app@0.2.3) (2020-09-25)

### Bug Fixes

* 忽略 pages 目录下的测试文件 ([9d0802f](https://github.com/twinh/miaoxing/commit/9d0802fed666a1ba7df6a832b6d4e8a0fb440135))
* 生成页面覆盖会被其他插件覆盖 ([3f9bd13](https://github.com/twinh/miaoxing/commit/3f9bd13785fac95f8c6c35d4c468c469113c3cc1))

### Dependencies

* **@miaoxing/dev:** upgrade from 6.1.1 to 6.1.2
* **@miaoxing/plugin:** upgrade from 0.2.2 to 0.2.3
* **@miaoxing/services:** upgrade from 0.2.2 to 0.2.3

# @miaoxing/admin

## [0.2.3](https://github.com/twinh/miaoxing/compare/@miaoxing/admin@0.2.2...@miaoxing/admin@0.2.3) (2020-09-25)

### Dependencies

* **miaoxing:** upgrade from 0.1.4 to 0.1.5
* **@miaoxing/dev:** upgrade from 6.1.1 to 6.1.2
* **@miaoxing/app:** upgrade from 0.2.2 to 0.2.3

# @miaoxing/region

# 0.1.0 (2020-09-25)

### Features

* init ([a263fc4](https://github.com/twinh/miaoxing/commit/a263fc4e3ff67cf742306a2405304b8225c73430))

### Dependencies

* **@miaoxing/app:** upgrade from 0.2.2 to 0.2.3

# @miaoxing/address

# 0.1.0 (2020-09-25)

### Features

* init ([56088cb](https://github.com/twinh/miaoxing/commit/56088cb76a969b301de38cc46af02675e8fb4275))

### Dependencies

* **@miaoxing/app:** upgrade from 0.2.2 to 0.2.3
* **@miaoxing/region:** upgrade to 0.1.0

# @miaoxing/captcha

## [0.1.11](https://github.com/twinh/miaoxing/compare/@miaoxing/captcha@0.1.10...@miaoxing/captcha@0.1.11) (2020-09-25)

### Dependencies

* **@miaoxing/plugin:** upgrade from 0.2.2 to 0.2.3
* **@miaoxing/dev:** upgrade from 6.1.1 to 6.1.2

# @miaoxing/link-to

## [0.1.3](https://github.com/twinh/miaoxing/compare/@miaoxing/link-to@0.1.2...@miaoxing/link-to@0.1.3) (2020-09-25)

### Dependencies

* **@miaoxing/app:** upgrade from 0.2.2 to 0.2.3

# @miaoxing/category

# 0.1.0 (2020-09-25)

### Features

* init ([6e6bc08](https://github.com/twinh/miaoxing/commit/6e6bc084723bcd9f9553ad81db80da30669f8e9c))
* init ([56088cb](https://github.com/twinh/miaoxing/commit/56088cb76a969b301de38cc46af02675e8fb4275))

### Dependencies

* **@miaoxing/dev:** upgrade from 6.1.1 to 6.1.2
* **@mxjs/test:** upgrade to 0.1.0
* **jest-preset-miaoxing:** upgrade from 0.2.0 to 0.2.1
* **@miaoxing/app:** upgrade from 0.2.2 to 0.2.3
* **@miaoxing/link-to:** upgrade from 0.1.2 to 0.1.3

# @miaoxing/config

## [0.1.11](https://github.com/twinh/miaoxing/compare/@miaoxing/config@0.1.10...@miaoxing/config@0.1.11) (2020-09-25)

### Dependencies

* **@miaoxing/app:** upgrade from 0.2.2 to 0.2.3

# @miaoxing/install

## [0.2.3](https://github.com/twinh/miaoxing/compare/@miaoxing/install@0.2.2...@miaoxing/install@0.2.3) (2020-09-25)

### Dependencies

* **@miaoxing/dev:** upgrade from 6.1.1 to 6.1.2
* **@miaoxing/plugin:** upgrade from 0.2.2 to 0.2.3
* **@miaoxing/services:** upgrade from 0.2.2 to 0.2.3

# @miaoxing/logistics

# 0.1.0 (2020-09-25)

### Features

* init ([56088cb](https://github.com/twinh/miaoxing/commit/56088cb76a969b301de38cc46af02675e8fb4275))

### Dependencies

* **@miaoxing/app:** upgrade from 0.2.2 to 0.2.3
* **@miaoxing/region:** upgrade to 0.1.0

# @miaoxing/mail

## [0.1.3](https://github.com/twinh/miaoxing/compare/@miaoxing/mail@0.1.2...@miaoxing/mail@0.1.3) (2020-09-25)

### Dependencies

* **@miaoxing/app:** upgrade from 0.2.2 to 0.2.3

# @miaoxing/nav

## [0.1.3](https://github.com/twinh/miaoxing/compare/@miaoxing/nav@0.1.2...@miaoxing/nav@0.1.3) (2020-09-25)

### Dependencies

* **@miaoxing/app:** upgrade from 0.2.2 to 0.2.3
* **@miaoxing/link-to:** upgrade from 0.1.2 to 0.1.3

# @miaoxing/product

# 0.1.0 (2020-09-25)

### Features

* init ([56088cb](https://github.com/twinh/miaoxing/commit/56088cb76a969b301de38cc46af02675e8fb4275))

### Dependencies

* **@miaoxing/app:** upgrade from 0.2.2 to 0.2.3
* **@miaoxing/category:** upgrade to 0.1.0
* **@miaoxing/admin:** upgrade from 0.2.2 to 0.2.3
* **@miaoxing/nav:** upgrade from 0.1.2 to 0.1.3

# @miaoxing/payment

# 0.1.0 (2020-09-25)

### Features

* init ([56088cb](https://github.com/twinh/miaoxing/commit/56088cb76a969b301de38cc46af02675e8fb4275))

### Dependencies

* **@miaoxing/app:** upgrade from 0.2.2 to 0.2.3
* **@miaoxing/product:** upgrade to 0.1.0

# @miaoxing/queue

## [0.1.11](https://github.com/twinh/miaoxing/compare/@miaoxing/queue@0.1.10...@miaoxing/queue@0.1.11) (2020-09-25)

### Dependencies

* **@miaoxing/app:** upgrade from 0.2.2 to 0.2.3

# @miaoxing/seq

## [0.1.11](https://github.com/twinh/miaoxing/compare/@miaoxing/seq@0.1.10...@miaoxing/seq@0.1.11) (2020-09-25)

### Dependencies

* **@miaoxing/app:** upgrade from 0.2.2 to 0.2.3

# @miaoxing/sms

## [0.1.3](https://github.com/twinh/miaoxing/compare/@miaoxing/sms@0.1.2...@miaoxing/sms@0.1.3) (2020-09-25)

### Dependencies

* **@miaoxing/app:** upgrade from 0.2.2 to 0.2.3

# @miaoxing/verify-code

## [0.1.3](https://github.com/twinh/miaoxing/compare/@miaoxing/verify-code@0.1.2...@miaoxing/verify-code@0.1.3) (2020-09-25)

### Dependencies

* **@miaoxing/sms:** upgrade from 0.1.2 to 0.1.3
* **@miaoxing/app:** upgrade from 0.2.2 to 0.2.3

# @miaoxing/user

## [0.1.12](https://github.com/twinh/miaoxing/compare/@miaoxing/user@0.1.11...@miaoxing/user@0.1.12) (2020-09-25)

### Bug Fixes

* toArray 缺少 isMobileVerified 字段 ([6bb9bd7](https://github.com/twinh/miaoxing/commit/6bb9bd71dc9e8f94016839922f6b8a51d3a1ea96))
* 从数据库读取头像为空字符串时，未转换成默认头像 ([97a6d6b](https://github.com/twinh/miaoxing/commit/97a6d6beff5fc708e7639164e03568a9aa6228b9))

### Features

* 增加后台用户列表 ([06c4956](https://github.com/twinh/miaoxing/commit/06c4956a76e282d934d6f5eb93dc1098ba179c79))
* 增加后台编辑用户功能 ([bc498fc](https://github.com/twinh/miaoxing/commit/bc498fc8f327e9b1d58b6edd3377e79f254181a9))
* 增加查询用户列表功能 ([0e2b729](https://github.com/twinh/miaoxing/commit/0e2b729257c21a365a73d1f1f70a75e9215d24b0))
* 增加用户卡片，鼠标移到用户头像上，显示用户详细信息 ([b9c8bf3](https://github.com/twinh/miaoxing/commit/b9c8bf399c228cb65f610c0e14a68337d4edaf6b))

### Dependencies

* **@mxjs/bootstrap:** upgrade from 0.1.0 to 0.1.1
* **@miaoxing/dev:** upgrade from 6.1.1 to 6.1.2
* **@miaoxing/app:** upgrade from 0.2.2 to 0.2.3
* **@miaoxing/verify-code:** upgrade from 0.1.2 to 0.1.3
* **@miaoxing/admin:** upgrade from 0.2.2 to 0.2.3
* **@miaoxing/mail:** upgrade from 0.1.2 to 0.1.3
* **@miaoxing/nav:** upgrade from 0.1.2 to 0.1.3
* **@miaoxing/region:** upgrade to 0.1.0

# @miaoxing/cart

# 0.1.0 (2020-09-25)

### Features

* init ([56088cb](https://github.com/twinh/miaoxing/commit/56088cb76a969b301de38cc46af02675e8fb4275))

### Dependencies

* **@miaoxing/app:** upgrade from 0.2.2 to 0.2.3
* **@miaoxing/product:** upgrade to 0.1.0
* **@miaoxing/user:** upgrade from 0.1.11 to 0.1.12

# @miaoxing/order

# 0.1.0 (2020-09-25)

### Features

* init ([56088cb](https://github.com/twinh/miaoxing/commit/56088cb76a969b301de38cc46af02675e8fb4275))

### Dependencies

* **@miaoxing/app:** upgrade from 0.2.2 to 0.2.3
* **@miaoxing/product:** upgrade to 0.1.0
* **@miaoxing/cart:** upgrade to 0.1.0
* **@miaoxing/payment:** upgrade to 0.1.0
* **@miaoxing/address:** upgrade to 0.1.0
* **@miaoxing/user:** upgrade from 0.1.11 to 0.1.12
* **@miaoxing/logistics:** upgrade to 0.1.0

# @miaoxing/refund

# 0.1.0 (2020-09-25)

### Features

* init ([56088cb](https://github.com/twinh/miaoxing/commit/56088cb76a969b301de38cc46af02675e8fb4275))

### Dependencies

* **@miaoxing/app:** upgrade from 0.2.2 to 0.2.3
* **@miaoxing/order:** upgrade to 0.1.0